---
title: "guide website"
author: "Sabina Pedrazzini"
output: html_document
email_adress: sabina.pedrazzini@unibe.ch
github_repo: https://github.com/sabinapedrazzini
---

# from R Markdown to webpage: basics

1.  Create a git repo for the project
2.  Create a Rmd file called index.Rmd =\> this is what will be displayed on the main page of the website
3.  In github, go to Setting \> Pages and activate it
4.  This will create a link toward the website
5.  Modify the index file on the main branch will modify the website

# change the styling

a css chunk will allow to change the appearance of the website (put echo=FALSE in the chunk option to avoid displaying it in the website)

in the website, right-clic \> inspect will opens the code for the different elements, so that it is easy to rely the code with the element + modify it in the css chunk

vw for font-size adapts the size to the size of the window

```{css}
.author, .title{
  display: none;
}
body{
  background: aliceblue;
  color: deeppink;
  font-size: 2vw;
}
```

# hyperlink

-   text to display in square brackets

-   link/email in normal brackets (they have to be in the yml)

[githubwebsite](`r rmarkdown::metadata$guthub_repo`)

[email](mailto:`r rmarkdown::metadata$email_adress`)

# date

```{r warning=FALSE}
library(lubridate)
```

`r today()` =\> this will display the date of the day without needing to modify it
